package com.example.demo.entity.domain;

import java.time.LocalDateTime;

public class CurrencyMst {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURRENCY_MST.CURRENCY_SEQ
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    private Long currencySeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURRENCY_MST.CURRENCY
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURRENCY_MST.ENTER_DATE
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    private LocalDateTime enterDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURRENCY_MST.ENTER_USER
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    private String enterUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURRENCY_MST.UPDATE_DATE
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    private LocalDateTime updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURRENCY_MST.UPDATE_USER
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURRENCY_MST.CURRENCY_SEQ
     *
     * @return the value of CURRENCY_MST.CURRENCY_SEQ
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    public Long getCurrencySeq() {
        return currencySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURRENCY_MST.CURRENCY_SEQ
     *
     * @param currencySeq the value for CURRENCY_MST.CURRENCY_SEQ
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    public void setCurrencySeq(Long currencySeq) {
        this.currencySeq = currencySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURRENCY_MST.CURRENCY
     *
     * @return the value of CURRENCY_MST.CURRENCY
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURRENCY_MST.CURRENCY
     *
     * @param currency the value for CURRENCY_MST.CURRENCY
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURRENCY_MST.ENTER_DATE
     *
     * @return the value of CURRENCY_MST.ENTER_DATE
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    public LocalDateTime getEnterDate() {
        return enterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURRENCY_MST.ENTER_DATE
     *
     * @param enterDate the value for CURRENCY_MST.ENTER_DATE
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    public void setEnterDate(LocalDateTime enterDate) {
        this.enterDate = enterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURRENCY_MST.ENTER_USER
     *
     * @return the value of CURRENCY_MST.ENTER_USER
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    public String getEnterUser() {
        return enterUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURRENCY_MST.ENTER_USER
     *
     * @param enterUser the value for CURRENCY_MST.ENTER_USER
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    public void setEnterUser(String enterUser) {
        this.enterUser = enterUser == null ? null : enterUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURRENCY_MST.UPDATE_DATE
     *
     * @return the value of CURRENCY_MST.UPDATE_DATE
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURRENCY_MST.UPDATE_DATE
     *
     * @param updateDate the value for CURRENCY_MST.UPDATE_DATE
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURRENCY_MST.UPDATE_USER
     *
     * @return the value of CURRENCY_MST.UPDATE_USER
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURRENCY_MST.UPDATE_USER
     *
     * @param updateUser the value for CURRENCY_MST.UPDATE_USER
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}