package com.example.demo.entity.domain;

import java.time.LocalDateTime;
import java.math.BigDecimal;

public class ProductMst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.PRODUCT_SEQ
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private Long productSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.PRODUCT_CODE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private String productCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.PRODUCT_NAME
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.PRODUCT_GENRE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private String productGenre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.PRODUCT_SIZE_STANDARD
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private String productSizeStandard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.PRODUCT_COLOR
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private String productColor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.PRODUCT_CURRENCY
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private String productCurrency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.PRODUCT_UNIT_PRICE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private BigDecimal productUnitPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.END_OF_SALE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private Boolean endOfSale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.END_OF_SALE_DATE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private LocalDateTime endOfSaleDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.ENTER_DATE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private LocalDateTime enterDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.ENTER_USER
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private String enterUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.UPDATE_DATE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private LocalDateTime updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_MST.UPDATE_USER
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.PRODUCT_SEQ
	 * @return  the value of PRODUCT_MST.PRODUCT_SEQ
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public Long getProductSeq() {
		return productSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.PRODUCT_SEQ
	 * @param productSeq  the value for PRODUCT_MST.PRODUCT_SEQ
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setProductSeq(Long productSeq) {
		this.productSeq = productSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.PRODUCT_CODE
	 * @return  the value of PRODUCT_MST.PRODUCT_CODE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public String getProductCode() {
		return productCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.PRODUCT_CODE
	 * @param productCode  the value for PRODUCT_MST.PRODUCT_CODE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode == null ? null : productCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.PRODUCT_NAME
	 * @return  the value of PRODUCT_MST.PRODUCT_NAME
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.PRODUCT_NAME
	 * @param productName  the value for PRODUCT_MST.PRODUCT_NAME
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setProductName(String productName) {
		this.productName = productName == null ? null : productName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.PRODUCT_GENRE
	 * @return  the value of PRODUCT_MST.PRODUCT_GENRE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public String getProductGenre() {
		return productGenre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.PRODUCT_GENRE
	 * @param productGenre  the value for PRODUCT_MST.PRODUCT_GENRE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setProductGenre(String productGenre) {
		this.productGenre = productGenre == null ? null : productGenre.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.PRODUCT_SIZE_STANDARD
	 * @return  the value of PRODUCT_MST.PRODUCT_SIZE_STANDARD
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public String getProductSizeStandard() {
		return productSizeStandard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.PRODUCT_SIZE_STANDARD
	 * @param productSizeStandard  the value for PRODUCT_MST.PRODUCT_SIZE_STANDARD
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setProductSizeStandard(String productSizeStandard) {
		this.productSizeStandard = productSizeStandard == null ? null : productSizeStandard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.PRODUCT_COLOR
	 * @return  the value of PRODUCT_MST.PRODUCT_COLOR
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public String getProductColor() {
		return productColor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.PRODUCT_COLOR
	 * @param productColor  the value for PRODUCT_MST.PRODUCT_COLOR
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setProductColor(String productColor) {
		this.productColor = productColor == null ? null : productColor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.PRODUCT_CURRENCY
	 * @return  the value of PRODUCT_MST.PRODUCT_CURRENCY
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public String getProductCurrency() {
		return productCurrency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.PRODUCT_CURRENCY
	 * @param productCurrency  the value for PRODUCT_MST.PRODUCT_CURRENCY
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setProductCurrency(String productCurrency) {
		this.productCurrency = productCurrency == null ? null : productCurrency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.PRODUCT_UNIT_PRICE
	 * @return  the value of PRODUCT_MST.PRODUCT_UNIT_PRICE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public BigDecimal getProductUnitPrice() {
		return productUnitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.PRODUCT_UNIT_PRICE
	 * @param productUnitPrice  the value for PRODUCT_MST.PRODUCT_UNIT_PRICE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setProductUnitPrice(BigDecimal productUnitPrice) {
		this.productUnitPrice = productUnitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.END_OF_SALE
	 * @return  the value of PRODUCT_MST.END_OF_SALE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public Boolean getEndOfSale() {
		return endOfSale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.END_OF_SALE
	 * @param endOfSale  the value for PRODUCT_MST.END_OF_SALE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setEndOfSale(Boolean endOfSale) {
		this.endOfSale = endOfSale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.END_OF_SALE_DATE
	 * @return  the value of PRODUCT_MST.END_OF_SALE_DATE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public LocalDateTime getEndOfSaleDate() {
		return endOfSaleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.END_OF_SALE_DATE
	 * @param endOfSaleDate  the value for PRODUCT_MST.END_OF_SALE_DATE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setEndOfSaleDate(LocalDateTime endOfSaleDate) {
		this.endOfSaleDate = endOfSaleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.ENTER_DATE
	 * @return  the value of PRODUCT_MST.ENTER_DATE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public LocalDateTime getEnterDate() {
		return enterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.ENTER_DATE
	 * @param enterDate  the value for PRODUCT_MST.ENTER_DATE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setEnterDate(LocalDateTime enterDate) {
		this.enterDate = enterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.ENTER_USER
	 * @return  the value of PRODUCT_MST.ENTER_USER
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public String getEnterUser() {
		return enterUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.ENTER_USER
	 * @param enterUser  the value for PRODUCT_MST.ENTER_USER
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setEnterUser(String enterUser) {
		this.enterUser = enterUser == null ? null : enterUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.UPDATE_DATE
	 * @return  the value of PRODUCT_MST.UPDATE_DATE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public LocalDateTime getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.UPDATE_DATE
	 * @param updateDate  the value for PRODUCT_MST.UPDATE_DATE
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setUpdateDate(LocalDateTime updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_MST.UPDATE_USER
	 * @return  the value of PRODUCT_MST.UPDATE_USER
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_MST.UPDATE_USER
	 * @param updateUser  the value for PRODUCT_MST.UPDATE_USER
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}
}