package com.example.demo.entity.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class UserMstExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	public UserMstExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserSeqIsNull() {
			addCriterion("USER_SEQ is null");
			return (Criteria) this;
		}

		public Criteria andUserSeqIsNotNull() {
			addCriterion("USER_SEQ is not null");
			return (Criteria) this;
		}

		public Criteria andUserSeqEqualTo(Long value) {
			addCriterion("USER_SEQ =", value, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqNotEqualTo(Long value) {
			addCriterion("USER_SEQ <>", value, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqGreaterThan(Long value) {
			addCriterion("USER_SEQ >", value, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqGreaterThanOrEqualTo(Long value) {
			addCriterion("USER_SEQ >=", value, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqLessThan(Long value) {
			addCriterion("USER_SEQ <", value, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqLessThanOrEqualTo(Long value) {
			addCriterion("USER_SEQ <=", value, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqIn(List<Long> values) {
			addCriterion("USER_SEQ in", values, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqNotIn(List<Long> values) {
			addCriterion("USER_SEQ not in", values, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqBetween(Long value1, Long value2) {
			addCriterion("USER_SEQ between", value1, value2, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqNotBetween(Long value1, Long value2) {
			addCriterion("USER_SEQ not between", value1, value2, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserAccountIsNull() {
			addCriterion("USER_ACCOUNT is null");
			return (Criteria) this;
		}

		public Criteria andUserAccountIsNotNull() {
			addCriterion("USER_ACCOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andUserAccountEqualTo(String value) {
			addCriterion("USER_ACCOUNT =", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountNotEqualTo(String value) {
			addCriterion("USER_ACCOUNT <>", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountGreaterThan(String value) {
			addCriterion("USER_ACCOUNT >", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountGreaterThanOrEqualTo(String value) {
			addCriterion("USER_ACCOUNT >=", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountLessThan(String value) {
			addCriterion("USER_ACCOUNT <", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountLessThanOrEqualTo(String value) {
			addCriterion("USER_ACCOUNT <=", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountLike(String value) {
			addCriterion("USER_ACCOUNT like", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountNotLike(String value) {
			addCriterion("USER_ACCOUNT not like", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountIn(List<String> values) {
			addCriterion("USER_ACCOUNT in", values, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountNotIn(List<String> values) {
			addCriterion("USER_ACCOUNT not in", values, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountBetween(String value1, String value2) {
			addCriterion("USER_ACCOUNT between", value1, value2, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountNotBetween(String value1, String value2) {
			addCriterion("USER_ACCOUNT not between", value1, value2, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordIsNull() {
			addCriterion("USER_ENCODED_PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordIsNotNull() {
			addCriterion("USER_ENCODED_PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordEqualTo(String value) {
			addCriterion("USER_ENCODED_PASSWORD =", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordNotEqualTo(String value) {
			addCriterion("USER_ENCODED_PASSWORD <>", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordGreaterThan(String value) {
			addCriterion("USER_ENCODED_PASSWORD >", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("USER_ENCODED_PASSWORD >=", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordLessThan(String value) {
			addCriterion("USER_ENCODED_PASSWORD <", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordLessThanOrEqualTo(String value) {
			addCriterion("USER_ENCODED_PASSWORD <=", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordLike(String value) {
			addCriterion("USER_ENCODED_PASSWORD like", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordNotLike(String value) {
			addCriterion("USER_ENCODED_PASSWORD not like", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordIn(List<String> values) {
			addCriterion("USER_ENCODED_PASSWORD in", values, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordNotIn(List<String> values) {
			addCriterion("USER_ENCODED_PASSWORD not in", values, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordBetween(String value1, String value2) {
			addCriterion("USER_ENCODED_PASSWORD between", value1, value2, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordNotBetween(String value1, String value2) {
			addCriterion("USER_ENCODED_PASSWORD not between", value1, value2, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("USER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("USER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("USER_NAME =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("USER_NAME <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("USER_NAME >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("USER_NAME >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("USER_NAME <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("USER_NAME <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("USER_NAME like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("USER_NAME not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("USER_NAME in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("USER_NAME not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("USER_NAME between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("USER_NAME not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserLocaleIsNull() {
			addCriterion("USER_LOCALE is null");
			return (Criteria) this;
		}

		public Criteria andUserLocaleIsNotNull() {
			addCriterion("USER_LOCALE is not null");
			return (Criteria) this;
		}

		public Criteria andUserLocaleEqualTo(String value) {
			addCriterion("USER_LOCALE =", value, "userLocale");
			return (Criteria) this;
		}

		public Criteria andUserLocaleNotEqualTo(String value) {
			addCriterion("USER_LOCALE <>", value, "userLocale");
			return (Criteria) this;
		}

		public Criteria andUserLocaleGreaterThan(String value) {
			addCriterion("USER_LOCALE >", value, "userLocale");
			return (Criteria) this;
		}

		public Criteria andUserLocaleGreaterThanOrEqualTo(String value) {
			addCriterion("USER_LOCALE >=", value, "userLocale");
			return (Criteria) this;
		}

		public Criteria andUserLocaleLessThan(String value) {
			addCriterion("USER_LOCALE <", value, "userLocale");
			return (Criteria) this;
		}

		public Criteria andUserLocaleLessThanOrEqualTo(String value) {
			addCriterion("USER_LOCALE <=", value, "userLocale");
			return (Criteria) this;
		}

		public Criteria andUserLocaleLike(String value) {
			addCriterion("USER_LOCALE like", value, "userLocale");
			return (Criteria) this;
		}

		public Criteria andUserLocaleNotLike(String value) {
			addCriterion("USER_LOCALE not like", value, "userLocale");
			return (Criteria) this;
		}

		public Criteria andUserLocaleIn(List<String> values) {
			addCriterion("USER_LOCALE in", values, "userLocale");
			return (Criteria) this;
		}

		public Criteria andUserLocaleNotIn(List<String> values) {
			addCriterion("USER_LOCALE not in", values, "userLocale");
			return (Criteria) this;
		}

		public Criteria andUserLocaleBetween(String value1, String value2) {
			addCriterion("USER_LOCALE between", value1, value2, "userLocale");
			return (Criteria) this;
		}

		public Criteria andUserLocaleNotBetween(String value1, String value2) {
			addCriterion("USER_LOCALE not between", value1, value2, "userLocale");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneIsNull() {
			addCriterion("USER_TIMEZONE is null");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneIsNotNull() {
			addCriterion("USER_TIMEZONE is not null");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneEqualTo(String value) {
			addCriterion("USER_TIMEZONE =", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneNotEqualTo(String value) {
			addCriterion("USER_TIMEZONE <>", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneGreaterThan(String value) {
			addCriterion("USER_TIMEZONE >", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneGreaterThanOrEqualTo(String value) {
			addCriterion("USER_TIMEZONE >=", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneLessThan(String value) {
			addCriterion("USER_TIMEZONE <", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneLessThanOrEqualTo(String value) {
			addCriterion("USER_TIMEZONE <=", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneLike(String value) {
			addCriterion("USER_TIMEZONE like", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneNotLike(String value) {
			addCriterion("USER_TIMEZONE not like", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneIn(List<String> values) {
			addCriterion("USER_TIMEZONE in", values, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneNotIn(List<String> values) {
			addCriterion("USER_TIMEZONE not in", values, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneBetween(String value1, String value2) {
			addCriterion("USER_TIMEZONE between", value1, value2, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneNotBetween(String value1, String value2) {
			addCriterion("USER_TIMEZONE not between", value1, value2, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetIsNull() {
			addCriterion("USER_TIMEZONE_OFFSET is null");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetIsNotNull() {
			addCriterion("USER_TIMEZONE_OFFSET is not null");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetEqualTo(String value) {
			addCriterion("USER_TIMEZONE_OFFSET =", value, "userTimezoneOffset");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetNotEqualTo(String value) {
			addCriterion("USER_TIMEZONE_OFFSET <>", value, "userTimezoneOffset");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetGreaterThan(String value) {
			addCriterion("USER_TIMEZONE_OFFSET >", value, "userTimezoneOffset");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetGreaterThanOrEqualTo(String value) {
			addCriterion("USER_TIMEZONE_OFFSET >=", value, "userTimezoneOffset");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetLessThan(String value) {
			addCriterion("USER_TIMEZONE_OFFSET <", value, "userTimezoneOffset");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetLessThanOrEqualTo(String value) {
			addCriterion("USER_TIMEZONE_OFFSET <=", value, "userTimezoneOffset");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetLike(String value) {
			addCriterion("USER_TIMEZONE_OFFSET like", value, "userTimezoneOffset");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetNotLike(String value) {
			addCriterion("USER_TIMEZONE_OFFSET not like", value, "userTimezoneOffset");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetIn(List<String> values) {
			addCriterion("USER_TIMEZONE_OFFSET in", values, "userTimezoneOffset");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetNotIn(List<String> values) {
			addCriterion("USER_TIMEZONE_OFFSET not in", values, "userTimezoneOffset");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetBetween(String value1, String value2) {
			addCriterion("USER_TIMEZONE_OFFSET between", value1, value2, "userTimezoneOffset");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneOffsetNotBetween(String value1, String value2) {
			addCriterion("USER_TIMEZONE_OFFSET not between", value1, value2, "userTimezoneOffset");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyIsNull() {
			addCriterion("USER_CURRENCY is null");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyIsNotNull() {
			addCriterion("USER_CURRENCY is not null");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyEqualTo(String value) {
			addCriterion("USER_CURRENCY =", value, "userCurrency");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyNotEqualTo(String value) {
			addCriterion("USER_CURRENCY <>", value, "userCurrency");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyGreaterThan(String value) {
			addCriterion("USER_CURRENCY >", value, "userCurrency");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyGreaterThanOrEqualTo(String value) {
			addCriterion("USER_CURRENCY >=", value, "userCurrency");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyLessThan(String value) {
			addCriterion("USER_CURRENCY <", value, "userCurrency");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyLessThanOrEqualTo(String value) {
			addCriterion("USER_CURRENCY <=", value, "userCurrency");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyLike(String value) {
			addCriterion("USER_CURRENCY like", value, "userCurrency");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyNotLike(String value) {
			addCriterion("USER_CURRENCY not like", value, "userCurrency");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyIn(List<String> values) {
			addCriterion("USER_CURRENCY in", values, "userCurrency");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyNotIn(List<String> values) {
			addCriterion("USER_CURRENCY not in", values, "userCurrency");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyBetween(String value1, String value2) {
			addCriterion("USER_CURRENCY between", value1, value2, "userCurrency");
			return (Criteria) this;
		}

		public Criteria andUserCurrencyNotBetween(String value1, String value2) {
			addCriterion("USER_CURRENCY not between", value1, value2, "userCurrency");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleIsNull() {
			addCriterion("USER_SUB_MENU_ROLE is null");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleIsNotNull() {
			addCriterion("USER_SUB_MENU_ROLE is not null");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleEqualTo(String value) {
			addCriterion("USER_SUB_MENU_ROLE =", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleNotEqualTo(String value) {
			addCriterion("USER_SUB_MENU_ROLE <>", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleGreaterThan(String value) {
			addCriterion("USER_SUB_MENU_ROLE >", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleGreaterThanOrEqualTo(String value) {
			addCriterion("USER_SUB_MENU_ROLE >=", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleLessThan(String value) {
			addCriterion("USER_SUB_MENU_ROLE <", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleLessThanOrEqualTo(String value) {
			addCriterion("USER_SUB_MENU_ROLE <=", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleLike(String value) {
			addCriterion("USER_SUB_MENU_ROLE like", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleNotLike(String value) {
			addCriterion("USER_SUB_MENU_ROLE not like", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleIn(List<String> values) {
			addCriterion("USER_SUB_MENU_ROLE in", values, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleNotIn(List<String> values) {
			addCriterion("USER_SUB_MENU_ROLE not in", values, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleBetween(String value1, String value2) {
			addCriterion("USER_SUB_MENU_ROLE between", value1, value2, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleNotBetween(String value1, String value2) {
			addCriterion("USER_SUB_MENU_ROLE not between", value1, value2, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andEnterDateIsNull() {
			addCriterion("ENTER_DATE is null");
			return (Criteria) this;
		}

		public Criteria andEnterDateIsNotNull() {
			addCriterion("ENTER_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andEnterDateEqualTo(LocalDateTime value) {
			addCriterion("ENTER_DATE =", value, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateNotEqualTo(LocalDateTime value) {
			addCriterion("ENTER_DATE <>", value, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateGreaterThan(LocalDateTime value) {
			addCriterion("ENTER_DATE >", value, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateGreaterThanOrEqualTo(LocalDateTime value) {
			addCriterion("ENTER_DATE >=", value, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateLessThan(LocalDateTime value) {
			addCriterion("ENTER_DATE <", value, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateLessThanOrEqualTo(LocalDateTime value) {
			addCriterion("ENTER_DATE <=", value, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateIn(List<LocalDateTime> values) {
			addCriterion("ENTER_DATE in", values, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateNotIn(List<LocalDateTime> values) {
			addCriterion("ENTER_DATE not in", values, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("ENTER_DATE between", value1, value2, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("ENTER_DATE not between", value1, value2, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterUserIsNull() {
			addCriterion("ENTER_USER is null");
			return (Criteria) this;
		}

		public Criteria andEnterUserIsNotNull() {
			addCriterion("ENTER_USER is not null");
			return (Criteria) this;
		}

		public Criteria andEnterUserEqualTo(String value) {
			addCriterion("ENTER_USER =", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserNotEqualTo(String value) {
			addCriterion("ENTER_USER <>", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserGreaterThan(String value) {
			addCriterion("ENTER_USER >", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserGreaterThanOrEqualTo(String value) {
			addCriterion("ENTER_USER >=", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserLessThan(String value) {
			addCriterion("ENTER_USER <", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserLessThanOrEqualTo(String value) {
			addCriterion("ENTER_USER <=", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserLike(String value) {
			addCriterion("ENTER_USER like", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserNotLike(String value) {
			addCriterion("ENTER_USER not like", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserIn(List<String> values) {
			addCriterion("ENTER_USER in", values, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserNotIn(List<String> values) {
			addCriterion("ENTER_USER not in", values, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserBetween(String value1, String value2) {
			addCriterion("ENTER_USER between", value1, value2, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserNotBetween(String value1, String value2) {
			addCriterion("ENTER_USER not between", value1, value2, "enterUser");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("UPDATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("UPDATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(LocalDateTime value) {
			addCriterion("UPDATE_DATE =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(LocalDateTime value) {
			addCriterion("UPDATE_DATE <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(LocalDateTime value) {
			addCriterion("UPDATE_DATE >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(LocalDateTime value) {
			addCriterion("UPDATE_DATE >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(LocalDateTime value) {
			addCriterion("UPDATE_DATE <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(LocalDateTime value) {
			addCriterion("UPDATE_DATE <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<LocalDateTime> values) {
			addCriterion("UPDATE_DATE in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<LocalDateTime> values) {
			addCriterion("UPDATE_DATE not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("UPDATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("UPDATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(String value) {
			addCriterion("UPDATE_USER =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(String value) {
			addCriterion("UPDATE_USER <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(String value) {
			addCriterion("UPDATE_USER >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(String value) {
			addCriterion("UPDATE_USER <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLike(String value) {
			addCriterion("UPDATE_USER like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotLike(String value) {
			addCriterion("UPDATE_USER not like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<String> values) {
			addCriterion("UPDATE_USER in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<String> values) {
			addCriterion("UPDATE_USER not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(String value1, String value2) {
			addCriterion("UPDATE_USER between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(String value1, String value2) {
			addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table USER_MST
	 * @mbg.generated  Sat Feb 29 16:49:29 JST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table USER_MST
	 *
	 * @mbg.generated do_not_delete_during_merge Fri Oct 18 08:45:46 JST 2019
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}
}