package com.example.demo.mybatis;

import com.example.demo.entity.domain.ProductMst;
import com.example.demo.entity.domain.ProductMstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductMstMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_MST
	 * @mbg.generated  Sat Oct 19 23:35:57 JST 2019
	 */
	long countByExample(ProductMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_MST
	 * @mbg.generated  Sat Oct 19 23:35:57 JST 2019
	 */
	int deleteByExample(ProductMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_MST
	 * @mbg.generated  Sat Oct 19 23:35:57 JST 2019
	 */
	int deleteByPrimaryKey(Long productSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_MST
	 * @mbg.generated  Sat Oct 19 23:35:57 JST 2019
	 */
	int insert(ProductMst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_MST
	 * @mbg.generated  Sat Oct 19 23:35:57 JST 2019
	 */
	int insertSelective(ProductMst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_MST
	 * @mbg.generated  Sat Oct 19 23:35:57 JST 2019
	 */
	List<ProductMst> selectByExample(ProductMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_MST
	 * @mbg.generated  Sat Oct 19 23:35:57 JST 2019
	 */
	ProductMst selectByPrimaryKey(Long productSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_MST
	 * @mbg.generated  Sat Oct 19 23:35:57 JST 2019
	 */
	int updateByExampleSelective(@Param("record") ProductMst record, @Param("example") ProductMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_MST
	 * @mbg.generated  Sat Oct 19 23:35:57 JST 2019
	 */
	int updateByExample(@Param("record") ProductMst record, @Param("example") ProductMstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_MST
	 * @mbg.generated  Sat Oct 19 23:35:57 JST 2019
	 */
	int updateByPrimaryKeySelective(ProductMst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_MST
	 * @mbg.generated  Sat Oct 19 23:35:57 JST 2019
	 */
	int updateByPrimaryKey(ProductMst record);
}