package com.example.demo.mybatis;

import com.example.demo.entity.domain.ProductPurchaseTbl;
import com.example.demo.entity.domain.ProductPurchaseTblExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductPurchaseTblMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Oct 20 01:03:53 JST 2019
	 */
	long countByExample(ProductPurchaseTblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Oct 20 01:03:53 JST 2019
	 */
	int deleteByExample(ProductPurchaseTblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Oct 20 01:03:53 JST 2019
	 */
	int deleteByPrimaryKey(Long productPurchaseSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Oct 20 01:03:53 JST 2019
	 */
	int insert(ProductPurchaseTbl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Oct 20 01:03:53 JST 2019
	 */
	int insertSelective(ProductPurchaseTbl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Oct 20 01:03:53 JST 2019
	 */
	List<ProductPurchaseTbl> selectByExample(ProductPurchaseTblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Oct 20 01:03:53 JST 2019
	 */
	ProductPurchaseTbl selectByPrimaryKey(Long productPurchaseSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Oct 20 01:03:53 JST 2019
	 */
	int updateByExampleSelective(@Param("record") ProductPurchaseTbl record,
			@Param("example") ProductPurchaseTblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Oct 20 01:03:53 JST 2019
	 */
	int updateByExample(@Param("record") ProductPurchaseTbl record,
			@Param("example") ProductPurchaseTblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Oct 20 01:03:53 JST 2019
	 */
	int updateByPrimaryKeySelective(ProductPurchaseTbl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Oct 20 01:03:53 JST 2019
	 */
	int updateByPrimaryKey(ProductPurchaseTbl record);
}