package com.example.demo.repository;

import com.example.demo.entity.domain.CurrencyMst;
import com.example.demo.entity.domain.CurrencyMstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CurrencyMstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURRENCY_MST
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    long countByExample(CurrencyMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURRENCY_MST
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    int deleteByExample(CurrencyMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURRENCY_MST
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    int deleteByPrimaryKey(Long currencySeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURRENCY_MST
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    int insert(CurrencyMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURRENCY_MST
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    int insertSelective(CurrencyMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURRENCY_MST
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    List<CurrencyMst> selectByExample(CurrencyMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURRENCY_MST
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    CurrencyMst selectByPrimaryKey(Long currencySeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURRENCY_MST
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    int updateByExampleSelective(@Param("record") CurrencyMst record, @Param("example") CurrencyMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURRENCY_MST
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    int updateByExample(@Param("record") CurrencyMst record, @Param("example") CurrencyMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURRENCY_MST
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    int updateByPrimaryKeySelective(CurrencyMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURRENCY_MST
     *
     * @mbg.generated Sun Jan 10 22:06:11 JST 2021
     */
    int updateByPrimaryKey(CurrencyMst record);
}