package com.example.demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.demo.entity.domain.ProductMstProductPurchaseTbl;
import com.example.demo.entity.domain.ProductPurchaseTbl;
import com.example.demo.entity.domain.ProductPurchaseTblExample;

public interface ProductPurchaseTblMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	long countByExample(ProductPurchaseTblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	int deleteByExample(ProductPurchaseTblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	int deleteByPrimaryKey(Long productPurchaseSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	int insert(ProductPurchaseTbl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	int insertSelective(ProductPurchaseTbl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	List<ProductPurchaseTbl> selectByExample(ProductPurchaseTblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	ProductPurchaseTbl selectByPrimaryKey(Long productPurchaseSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	int updateByExampleSelective(@Param("record") ProductPurchaseTbl record,
			@Param("example") ProductPurchaseTblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	int updateByExample(@Param("record") ProductPurchaseTbl record,
			@Param("example") ProductPurchaseTblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	int updateByPrimaryKeySelective(ProductPurchaseTbl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRODUCT_PURCHASE_TBL
	 * @mbg.generated  Sun Jan 10 22:06:11 JST 2021
	 */
	int updateByPrimaryKey(ProductPurchaseTbl record);

	/**
	 * Counts product master joins parchase table redcords.
	 * @param productMstProductPurchaseTbl search conditions
	 * @return search results count
	 */
	long countProductMstProductPurchaseTbl(
			@Param("productMstProductPurchaseTbl") ProductMstProductPurchaseTbl productMstProductPurchaseTbl);

	/**
	 * Gets product master joins parchase table redcords.
	 * @param productMstProductPurchaseTbl search conditions
	 * @param limit limit size
	 * @param offset offset size
	 * @return search results
	 */
	List<ProductMstProductPurchaseTbl> selectProductMstProductPurchaseTbl(
			@Param("productMstProductPurchaseTbl") ProductMstProductPurchaseTbl productMstProductPurchaseTbl,
			@Param("limit") Integer limit, @Param("offset") Long offset);

}