package com.example.demo.repository;

import com.example.demo.entity.domain.UserMst;
import com.example.demo.entity.domain.UserMstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMstMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
   * @mbg.generated  Tue Feb 02 01:04:07 JST 2021
   */
  long countByExample(UserMstExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
   * @mbg.generated  Tue Feb 02 01:04:07 JST 2021
   */
  int deleteByExample(UserMstExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
   * @mbg.generated  Tue Feb 02 01:04:07 JST 2021
   */
  int deleteByPrimaryKey(Long userSeq);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
   * @mbg.generated  Tue Feb 02 01:04:07 JST 2021
   */
  int insert(UserMst record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
   * @mbg.generated  Tue Feb 02 01:04:07 JST 2021
   */
  int insertSelective(UserMst record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
   * @mbg.generated  Tue Feb 02 01:04:07 JST 2021
   */
  List<UserMst> selectByExample(UserMstExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
   * @mbg.generated  Tue Feb 02 01:04:07 JST 2021
   */
  UserMst selectByPrimaryKey(Long userSeq);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
   * @mbg.generated  Tue Feb 02 01:04:07 JST 2021
   */
  int updateByExampleSelective(@Param("record") UserMst record,
      @Param("example") UserMstExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
   * @mbg.generated  Tue Feb 02 01:04:07 JST 2021
   */
  int updateByExample(@Param("record") UserMst record, @Param("example") UserMstExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
   * @mbg.generated  Tue Feb 02 01:04:07 JST 2021
   */
  int updateByPrimaryKeySelective(UserMst record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
   * @mbg.generated  Tue Feb 02 01:04:07 JST 2021
   */
  int updateByPrimaryKey(UserMst record);
}