package com.example.demo.entity.domain;

import java.util.Date;

public class ProductStockMst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_STOCK_MST.PRODUCT_STOCK_SEQ
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private Long productStockSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_STOCK_MST.PRODUCT_SEQ
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private Long productSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_STOCK_MST.PRODUCT_STOCK_QUANTITY
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private Integer productStockQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_STOCK_MST.ENTER_DATE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private Date enterDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_STOCK_MST.ENTER_USER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private String enterUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_STOCK_MST.UPDATE_DATE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRODUCT_STOCK_MST.UPDATE_USER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_STOCK_MST.PRODUCT_STOCK_SEQ
	 * @return  the value of PRODUCT_STOCK_MST.PRODUCT_STOCK_SEQ
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public Long getProductStockSeq() {
		return productStockSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_STOCK_MST.PRODUCT_STOCK_SEQ
	 * @param productStockSeq  the value for PRODUCT_STOCK_MST.PRODUCT_STOCK_SEQ
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setProductStockSeq(Long productStockSeq) {
		this.productStockSeq = productStockSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_STOCK_MST.PRODUCT_SEQ
	 * @return  the value of PRODUCT_STOCK_MST.PRODUCT_SEQ
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public Long getProductSeq() {
		return productSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_STOCK_MST.PRODUCT_SEQ
	 * @param productSeq  the value for PRODUCT_STOCK_MST.PRODUCT_SEQ
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setProductSeq(Long productSeq) {
		this.productSeq = productSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_STOCK_MST.PRODUCT_STOCK_QUANTITY
	 * @return  the value of PRODUCT_STOCK_MST.PRODUCT_STOCK_QUANTITY
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public Integer getProductStockQuantity() {
		return productStockQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_STOCK_MST.PRODUCT_STOCK_QUANTITY
	 * @param productStockQuantity  the value for PRODUCT_STOCK_MST.PRODUCT_STOCK_QUANTITY
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setProductStockQuantity(Integer productStockQuantity) {
		this.productStockQuantity = productStockQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_STOCK_MST.ENTER_DATE
	 * @return  the value of PRODUCT_STOCK_MST.ENTER_DATE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public Date getEnterDate() {
		return enterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_STOCK_MST.ENTER_DATE
	 * @param enterDate  the value for PRODUCT_STOCK_MST.ENTER_DATE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setEnterDate(Date enterDate) {
		this.enterDate = enterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_STOCK_MST.ENTER_USER
	 * @return  the value of PRODUCT_STOCK_MST.ENTER_USER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public String getEnterUser() {
		return enterUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_STOCK_MST.ENTER_USER
	 * @param enterUser  the value for PRODUCT_STOCK_MST.ENTER_USER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setEnterUser(String enterUser) {
		this.enterUser = enterUser == null ? null : enterUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_STOCK_MST.UPDATE_DATE
	 * @return  the value of PRODUCT_STOCK_MST.UPDATE_DATE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_STOCK_MST.UPDATE_DATE
	 * @param updateDate  the value for PRODUCT_STOCK_MST.UPDATE_DATE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRODUCT_STOCK_MST.UPDATE_USER
	 * @return  the value of PRODUCT_STOCK_MST.UPDATE_USER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRODUCT_STOCK_MST.UPDATE_USER
	 * @param updateUser  the value for PRODUCT_STOCK_MST.UPDATE_USER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}
}