package com.example.demo.entity.domain;

import java.util.Date;

public class SubMenuMst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SUB_MENU_MST.SUB_MENU_SEQ
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private Long subMenuSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SUB_MENU_MST.SUB_MENU_CODE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private String subMenuCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SUB_MENU_MST.MENU_SEQ
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private Long menuSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SUB_MENU_MST.SUB_MENU_ROLL
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private String subMenuRoll;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SUB_MENU_MST.SUB_MENU_ORDER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private Short subMenuOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SUB_MENU_MST.ENTER_DATE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private Date enterDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SUB_MENU_MST.ENTER_USER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private String enterUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SUB_MENU_MST.UPDATE_DATE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SUB_MENU_MST.UPDATE_USER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SUB_MENU_MST.SUB_MENU_SEQ
	 * @return  the value of SUB_MENU_MST.SUB_MENU_SEQ
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public Long getSubMenuSeq() {
		return subMenuSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SUB_MENU_MST.SUB_MENU_SEQ
	 * @param subMenuSeq  the value for SUB_MENU_MST.SUB_MENU_SEQ
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setSubMenuSeq(Long subMenuSeq) {
		this.subMenuSeq = subMenuSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SUB_MENU_MST.SUB_MENU_CODE
	 * @return  the value of SUB_MENU_MST.SUB_MENU_CODE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public String getSubMenuCode() {
		return subMenuCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SUB_MENU_MST.SUB_MENU_CODE
	 * @param subMenuCode  the value for SUB_MENU_MST.SUB_MENU_CODE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setSubMenuCode(String subMenuCode) {
		this.subMenuCode = subMenuCode == null ? null : subMenuCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SUB_MENU_MST.MENU_SEQ
	 * @return  the value of SUB_MENU_MST.MENU_SEQ
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public Long getMenuSeq() {
		return menuSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SUB_MENU_MST.MENU_SEQ
	 * @param menuSeq  the value for SUB_MENU_MST.MENU_SEQ
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setMenuSeq(Long menuSeq) {
		this.menuSeq = menuSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SUB_MENU_MST.SUB_MENU_ROLL
	 * @return  the value of SUB_MENU_MST.SUB_MENU_ROLL
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public String getSubMenuRoll() {
		return subMenuRoll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SUB_MENU_MST.SUB_MENU_ROLL
	 * @param subMenuRoll  the value for SUB_MENU_MST.SUB_MENU_ROLL
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setSubMenuRoll(String subMenuRoll) {
		this.subMenuRoll = subMenuRoll == null ? null : subMenuRoll.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SUB_MENU_MST.SUB_MENU_ORDER
	 * @return  the value of SUB_MENU_MST.SUB_MENU_ORDER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public Short getSubMenuOrder() {
		return subMenuOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SUB_MENU_MST.SUB_MENU_ORDER
	 * @param subMenuOrder  the value for SUB_MENU_MST.SUB_MENU_ORDER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setSubMenuOrder(Short subMenuOrder) {
		this.subMenuOrder = subMenuOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SUB_MENU_MST.ENTER_DATE
	 * @return  the value of SUB_MENU_MST.ENTER_DATE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public Date getEnterDate() {
		return enterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SUB_MENU_MST.ENTER_DATE
	 * @param enterDate  the value for SUB_MENU_MST.ENTER_DATE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setEnterDate(Date enterDate) {
		this.enterDate = enterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SUB_MENU_MST.ENTER_USER
	 * @return  the value of SUB_MENU_MST.ENTER_USER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public String getEnterUser() {
		return enterUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SUB_MENU_MST.ENTER_USER
	 * @param enterUser  the value for SUB_MENU_MST.ENTER_USER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setEnterUser(String enterUser) {
		this.enterUser = enterUser == null ? null : enterUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SUB_MENU_MST.UPDATE_DATE
	 * @return  the value of SUB_MENU_MST.UPDATE_DATE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SUB_MENU_MST.UPDATE_DATE
	 * @param updateDate  the value for SUB_MENU_MST.UPDATE_DATE
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SUB_MENU_MST.UPDATE_USER
	 * @return  the value of SUB_MENU_MST.UPDATE_USER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SUB_MENU_MST.UPDATE_USER
	 * @param updateUser  the value for SUB_MENU_MST.UPDATE_USER
	 * @mbg.generated  Thu Jan 16 01:45:27 JST 2020
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}
}