package com.example.demo.entity.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserMstExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	public UserMstExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserSeqIsNull() {
			addCriterion("USER_SEQ is null");
			return (Criteria) this;
		}

		public Criteria andUserSeqIsNotNull() {
			addCriterion("USER_SEQ is not null");
			return (Criteria) this;
		}

		public Criteria andUserSeqEqualTo(Long value) {
			addCriterion("USER_SEQ =", value, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqNotEqualTo(Long value) {
			addCriterion("USER_SEQ <>", value, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqGreaterThan(Long value) {
			addCriterion("USER_SEQ >", value, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqGreaterThanOrEqualTo(Long value) {
			addCriterion("USER_SEQ >=", value, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqLessThan(Long value) {
			addCriterion("USER_SEQ <", value, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqLessThanOrEqualTo(Long value) {
			addCriterion("USER_SEQ <=", value, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqIn(List<Long> values) {
			addCriterion("USER_SEQ in", values, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqNotIn(List<Long> values) {
			addCriterion("USER_SEQ not in", values, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqBetween(Long value1, Long value2) {
			addCriterion("USER_SEQ between", value1, value2, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserSeqNotBetween(Long value1, Long value2) {
			addCriterion("USER_SEQ not between", value1, value2, "userSeq");
			return (Criteria) this;
		}

		public Criteria andUserAccountIsNull() {
			addCriterion("USER_ACCOUNT is null");
			return (Criteria) this;
		}

		public Criteria andUserAccountIsNotNull() {
			addCriterion("USER_ACCOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andUserAccountEqualTo(String value) {
			addCriterion("USER_ACCOUNT =", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountNotEqualTo(String value) {
			addCriterion("USER_ACCOUNT <>", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountGreaterThan(String value) {
			addCriterion("USER_ACCOUNT >", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountGreaterThanOrEqualTo(String value) {
			addCriterion("USER_ACCOUNT >=", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountLessThan(String value) {
			addCriterion("USER_ACCOUNT <", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountLessThanOrEqualTo(String value) {
			addCriterion("USER_ACCOUNT <=", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountLike(String value) {
			addCriterion("USER_ACCOUNT like", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountNotLike(String value) {
			addCriterion("USER_ACCOUNT not like", value, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountIn(List<String> values) {
			addCriterion("USER_ACCOUNT in", values, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountNotIn(List<String> values) {
			addCriterion("USER_ACCOUNT not in", values, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountBetween(String value1, String value2) {
			addCriterion("USER_ACCOUNT between", value1, value2, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserAccountNotBetween(String value1, String value2) {
			addCriterion("USER_ACCOUNT not between", value1, value2, "userAccount");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordIsNull() {
			addCriterion("USER_ENCODED_PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordIsNotNull() {
			addCriterion("USER_ENCODED_PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordEqualTo(String value) {
			addCriterion("USER_ENCODED_PASSWORD =", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordNotEqualTo(String value) {
			addCriterion("USER_ENCODED_PASSWORD <>", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordGreaterThan(String value) {
			addCriterion("USER_ENCODED_PASSWORD >", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("USER_ENCODED_PASSWORD >=", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordLessThan(String value) {
			addCriterion("USER_ENCODED_PASSWORD <", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordLessThanOrEqualTo(String value) {
			addCriterion("USER_ENCODED_PASSWORD <=", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordLike(String value) {
			addCriterion("USER_ENCODED_PASSWORD like", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordNotLike(String value) {
			addCriterion("USER_ENCODED_PASSWORD not like", value, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordIn(List<String> values) {
			addCriterion("USER_ENCODED_PASSWORD in", values, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordNotIn(List<String> values) {
			addCriterion("USER_ENCODED_PASSWORD not in", values, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordBetween(String value1, String value2) {
			addCriterion("USER_ENCODED_PASSWORD between", value1, value2, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserEncodedPasswordNotBetween(String value1, String value2) {
			addCriterion("USER_ENCODED_PASSWORD not between", value1, value2, "userEncodedPassword");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("USER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("USER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("USER_NAME =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("USER_NAME <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("USER_NAME >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("USER_NAME >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("USER_NAME <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("USER_NAME <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("USER_NAME like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("USER_NAME not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("USER_NAME in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("USER_NAME not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("USER_NAME between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("USER_NAME not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserLangIsNull() {
			addCriterion("USER_LANG is null");
			return (Criteria) this;
		}

		public Criteria andUserLangIsNotNull() {
			addCriterion("USER_LANG is not null");
			return (Criteria) this;
		}

		public Criteria andUserLangEqualTo(String value) {
			addCriterion("USER_LANG =", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangNotEqualTo(String value) {
			addCriterion("USER_LANG <>", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangGreaterThan(String value) {
			addCriterion("USER_LANG >", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangGreaterThanOrEqualTo(String value) {
			addCriterion("USER_LANG >=", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangLessThan(String value) {
			addCriterion("USER_LANG <", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangLessThanOrEqualTo(String value) {
			addCriterion("USER_LANG <=", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangLike(String value) {
			addCriterion("USER_LANG like", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangNotLike(String value) {
			addCriterion("USER_LANG not like", value, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangIn(List<String> values) {
			addCriterion("USER_LANG in", values, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangNotIn(List<String> values) {
			addCriterion("USER_LANG not in", values, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangBetween(String value1, String value2) {
			addCriterion("USER_LANG between", value1, value2, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserLangNotBetween(String value1, String value2) {
			addCriterion("USER_LANG not between", value1, value2, "userLang");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneIsNull() {
			addCriterion("USER_TIMEZONE is null");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneIsNotNull() {
			addCriterion("USER_TIMEZONE is not null");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneEqualTo(String value) {
			addCriterion("USER_TIMEZONE =", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneNotEqualTo(String value) {
			addCriterion("USER_TIMEZONE <>", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneGreaterThan(String value) {
			addCriterion("USER_TIMEZONE >", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneGreaterThanOrEqualTo(String value) {
			addCriterion("USER_TIMEZONE >=", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneLessThan(String value) {
			addCriterion("USER_TIMEZONE <", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneLessThanOrEqualTo(String value) {
			addCriterion("USER_TIMEZONE <=", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneLike(String value) {
			addCriterion("USER_TIMEZONE like", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneNotLike(String value) {
			addCriterion("USER_TIMEZONE not like", value, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneIn(List<String> values) {
			addCriterion("USER_TIMEZONE in", values, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneNotIn(List<String> values) {
			addCriterion("USER_TIMEZONE not in", values, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneBetween(String value1, String value2) {
			addCriterion("USER_TIMEZONE between", value1, value2, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserTimezoneNotBetween(String value1, String value2) {
			addCriterion("USER_TIMEZONE not between", value1, value2, "userTimezone");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleIsNull() {
			addCriterion("USER_SUB_MENU_ROLE is null");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleIsNotNull() {
			addCriterion("USER_SUB_MENU_ROLE is not null");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleEqualTo(String value) {
			addCriterion("USER_SUB_MENU_ROLE =", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleNotEqualTo(String value) {
			addCriterion("USER_SUB_MENU_ROLE <>", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleGreaterThan(String value) {
			addCriterion("USER_SUB_MENU_ROLE >", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleGreaterThanOrEqualTo(String value) {
			addCriterion("USER_SUB_MENU_ROLE >=", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleLessThan(String value) {
			addCriterion("USER_SUB_MENU_ROLE <", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleLessThanOrEqualTo(String value) {
			addCriterion("USER_SUB_MENU_ROLE <=", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleLike(String value) {
			addCriterion("USER_SUB_MENU_ROLE like", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleNotLike(String value) {
			addCriterion("USER_SUB_MENU_ROLE not like", value, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleIn(List<String> values) {
			addCriterion("USER_SUB_MENU_ROLE in", values, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleNotIn(List<String> values) {
			addCriterion("USER_SUB_MENU_ROLE not in", values, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleBetween(String value1, String value2) {
			addCriterion("USER_SUB_MENU_ROLE between", value1, value2, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andUserSubMenuRoleNotBetween(String value1, String value2) {
			addCriterion("USER_SUB_MENU_ROLE not between", value1, value2, "userSubMenuRole");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNull() {
			addCriterion("DELETED is null");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNotNull() {
			addCriterion("DELETED is not null");
			return (Criteria) this;
		}

		public Criteria andDeletedEqualTo(Boolean value) {
			addCriterion("DELETED =", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotEqualTo(Boolean value) {
			addCriterion("DELETED <>", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThan(Boolean value) {
			addCriterion("DELETED >", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("DELETED >=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThan(Boolean value) {
			addCriterion("DELETED <", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
			addCriterion("DELETED <=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedIn(List<Boolean> values) {
			addCriterion("DELETED in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotIn(List<Boolean> values) {
			addCriterion("DELETED not in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
			addCriterion("DELETED between", value1, value2, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("DELETED not between", value1, value2, "deleted");
			return (Criteria) this;
		}

		public Criteria andEnterDateIsNull() {
			addCriterion("ENTER_DATE is null");
			return (Criteria) this;
		}

		public Criteria andEnterDateIsNotNull() {
			addCriterion("ENTER_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andEnterDateEqualTo(Date value) {
			addCriterion("ENTER_DATE =", value, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateNotEqualTo(Date value) {
			addCriterion("ENTER_DATE <>", value, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateGreaterThan(Date value) {
			addCriterion("ENTER_DATE >", value, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateGreaterThanOrEqualTo(Date value) {
			addCriterion("ENTER_DATE >=", value, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateLessThan(Date value) {
			addCriterion("ENTER_DATE <", value, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateLessThanOrEqualTo(Date value) {
			addCriterion("ENTER_DATE <=", value, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateIn(List<Date> values) {
			addCriterion("ENTER_DATE in", values, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateNotIn(List<Date> values) {
			addCriterion("ENTER_DATE not in", values, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateBetween(Date value1, Date value2) {
			addCriterion("ENTER_DATE between", value1, value2, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterDateNotBetween(Date value1, Date value2) {
			addCriterion("ENTER_DATE not between", value1, value2, "enterDate");
			return (Criteria) this;
		}

		public Criteria andEnterUserIsNull() {
			addCriterion("ENTER_USER is null");
			return (Criteria) this;
		}

		public Criteria andEnterUserIsNotNull() {
			addCriterion("ENTER_USER is not null");
			return (Criteria) this;
		}

		public Criteria andEnterUserEqualTo(String value) {
			addCriterion("ENTER_USER =", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserNotEqualTo(String value) {
			addCriterion("ENTER_USER <>", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserGreaterThan(String value) {
			addCriterion("ENTER_USER >", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserGreaterThanOrEqualTo(String value) {
			addCriterion("ENTER_USER >=", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserLessThan(String value) {
			addCriterion("ENTER_USER <", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserLessThanOrEqualTo(String value) {
			addCriterion("ENTER_USER <=", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserLike(String value) {
			addCriterion("ENTER_USER like", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserNotLike(String value) {
			addCriterion("ENTER_USER not like", value, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserIn(List<String> values) {
			addCriterion("ENTER_USER in", values, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserNotIn(List<String> values) {
			addCriterion("ENTER_USER not in", values, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserBetween(String value1, String value2) {
			addCriterion("ENTER_USER between", value1, value2, "enterUser");
			return (Criteria) this;
		}

		public Criteria andEnterUserNotBetween(String value1, String value2) {
			addCriterion("ENTER_USER not between", value1, value2, "enterUser");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("UPDATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("UPDATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("UPDATE_DATE =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("UPDATE_DATE <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("UPDATE_DATE >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("UPDATE_DATE <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("UPDATE_DATE in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("UPDATE_DATE not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("UPDATE_USER is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("UPDATE_USER is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(String value) {
			addCriterion("UPDATE_USER =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(String value) {
			addCriterion("UPDATE_USER <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(String value) {
			addCriterion("UPDATE_USER >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(String value) {
			addCriterion("UPDATE_USER <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_USER <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLike(String value) {
			addCriterion("UPDATE_USER like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotLike(String value) {
			addCriterion("UPDATE_USER not like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<String> values) {
			addCriterion("UPDATE_USER in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<String> values) {
			addCriterion("UPDATE_USER not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(String value1, String value2) {
			addCriterion("UPDATE_USER between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(String value1, String value2) {
			addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table USER_MST
	 * @mbg.generated  Mon Oct 21 11:39:52 JST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_MST
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 18 08:45:46 JST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}