package com.example.demo.entity.domain;

import java.util.Date;
import java.time.LocalDateTime;

public class UserMst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_MST.USER_SEQ
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	private Long userSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_MST.USER_ACCOUNT
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	private String userAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_MST.USER_ENCODED_PASSWORD
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	private String userEncodedPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_MST.USER_NAME
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_MST.USER_LOCALE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	private String userLocale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_MST.USER_TIMEZONE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	private String userTimezone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_MST.USER_TIMEZONE_OFFSET
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	private String userTimezoneOffset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_MST.USER_CURRENCY
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	private String userCurrency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_MST.USER_SUB_MENU_ROLE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	private String userSubMenuRole;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_MST.ENTER_DATE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	private LocalDateTime enterDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_MST.ENTER_USER
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	private String enterUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_MST.UPDATE_DATE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	private LocalDateTime updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_MST.UPDATE_USER
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_MST.USER_SEQ
	 * @return  the value of USER_MST.USER_SEQ
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public Long getUserSeq() {
		return userSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_MST.USER_SEQ
	 * @param userSeq  the value for USER_MST.USER_SEQ
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public void setUserSeq(Long userSeq) {
		this.userSeq = userSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_MST.USER_ACCOUNT
	 * @return  the value of USER_MST.USER_ACCOUNT
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public String getUserAccount() {
		return userAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_MST.USER_ACCOUNT
	 * @param userAccount  the value for USER_MST.USER_ACCOUNT
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount == null ? null : userAccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_MST.USER_ENCODED_PASSWORD
	 * @return  the value of USER_MST.USER_ENCODED_PASSWORD
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public String getUserEncodedPassword() {
		return userEncodedPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_MST.USER_ENCODED_PASSWORD
	 * @param userEncodedPassword  the value for USER_MST.USER_ENCODED_PASSWORD
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public void setUserEncodedPassword(String userEncodedPassword) {
		this.userEncodedPassword = userEncodedPassword == null ? null : userEncodedPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_MST.USER_NAME
	 * @return  the value of USER_MST.USER_NAME
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_MST.USER_NAME
	 * @param userName  the value for USER_MST.USER_NAME
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_MST.USER_LOCALE
	 * @return  the value of USER_MST.USER_LOCALE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public String getUserLocale() {
		return userLocale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_MST.USER_LOCALE
	 * @param userLocale  the value for USER_MST.USER_LOCALE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public void setUserLocale(String userLocale) {
		this.userLocale = userLocale == null ? null : userLocale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_MST.USER_TIMEZONE
	 * @return  the value of USER_MST.USER_TIMEZONE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public String getUserTimezone() {
		return userTimezone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_MST.USER_TIMEZONE
	 * @param userTimezone  the value for USER_MST.USER_TIMEZONE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public void setUserTimezone(String userTimezone) {
		this.userTimezone = userTimezone == null ? null : userTimezone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_MST.USER_TIMEZONE_OFFSET
	 * @return  the value of USER_MST.USER_TIMEZONE_OFFSET
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public String getUserTimezoneOffset() {
		return userTimezoneOffset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_MST.USER_TIMEZONE_OFFSET
	 * @param userTimezoneOffset  the value for USER_MST.USER_TIMEZONE_OFFSET
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public void setUserTimezoneOffset(String userTimezoneOffset) {
		this.userTimezoneOffset = userTimezoneOffset == null ? null : userTimezoneOffset.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_MST.USER_CURRENCY
	 * @return  the value of USER_MST.USER_CURRENCY
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public String getUserCurrency() {
		return userCurrency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_MST.USER_CURRENCY
	 * @param userCurrency  the value for USER_MST.USER_CURRENCY
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public void setUserCurrency(String userCurrency) {
		this.userCurrency = userCurrency == null ? null : userCurrency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_MST.USER_SUB_MENU_ROLE
	 * @return  the value of USER_MST.USER_SUB_MENU_ROLE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public String getUserSubMenuRole() {
		return userSubMenuRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_MST.USER_SUB_MENU_ROLE
	 * @param userSubMenuRole  the value for USER_MST.USER_SUB_MENU_ROLE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public void setUserSubMenuRole(String userSubMenuRole) {
		this.userSubMenuRole = userSubMenuRole == null ? null : userSubMenuRole.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_MST.ENTER_DATE
	 * @return  the value of USER_MST.ENTER_DATE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public LocalDateTime getEnterDate() {
		return enterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_MST.ENTER_DATE
	 * @param enterDate  the value for USER_MST.ENTER_DATE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public void setEnterDate(LocalDateTime enterDate) {
		this.enterDate = enterDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_MST.ENTER_USER
	 * @return  the value of USER_MST.ENTER_USER
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public String getEnterUser() {
		return enterUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_MST.ENTER_USER
	 * @param enterUser  the value for USER_MST.ENTER_USER
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public void setEnterUser(String enterUser) {
		this.enterUser = enterUser == null ? null : enterUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_MST.UPDATE_DATE
	 * @return  the value of USER_MST.UPDATE_DATE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public LocalDateTime getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_MST.UPDATE_DATE
	 * @param updateDate  the value for USER_MST.UPDATE_DATE
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public void setUpdateDate(LocalDateTime updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER_MST.UPDATE_USER
	 * @return  the value of USER_MST.UPDATE_USER
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER_MST.UPDATE_USER
	 * @param updateUser  the value for USER_MST.UPDATE_USER
	 * @mbg.generated  Thu Jan 16 18:26:50 JST 2020
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}

	private static final String DELIMIT_LOCALE = "-";

	public String getUserLanguage() {

		String[] items = this.userLocale.split(DELIMIT_LOCALE);
		return items[0];

	}
}